CREATE TABLE [Stage].[Contracts] (
  [Id] [bigint] NOT NULL,
  [GID] [uniqueidentifier] NOT NULL,
  [ContragentGID] [uniqueidentifier] NOT NULL,
  [ContractNumber] [nvarchar](50) NOT NULL,
  [BranchGID] [uniqueidentifier] NOT NULL,
  [ContractTypeGID] [uniqueidentifier] NULL,
  [BeginDate] [date] NULL,
  [EndDate] [date] NULL,
  [Sum] [decimal](18, 2) NULL,
  [ResponsibleGID] [uniqueidentifier] NULL,
  [Deleted] [bit] NOT NULL,
  [Comment] [nvarchar](255) NULL,
  [AuthorGID] [uniqueidentifier] NULL,
  [CreateDate] [datetime] NULL,
  [CreatorUserGID] [uniqueidentifier] NULL,
  [LastModifiedDate] [datetime] NULL,
  [LastModifiedAuthorGID] [uniqueidentifier] NULL,
  [WorkflowGID] [uniqueidentifier] NULL,
  [StatusGID] [uniqueidentifier] NOT NULL,
  [ObjectsCount] [int] NULL,
  [ParentGID] [uniqueidentifier] NULL,
  [OwnerGID] [uniqueidentifier] NULL,
  [SalesChannelGID] [uniqueidentifier] NULL,
  [SubSalesChannelGID] [uniqueidentifier] NULL,
  [AgentPermissionGID] [uniqueidentifier] NULL,
  [RegisteredDate] [date] NULL,
  [_CreateDateTime] [datetime2] NOT NULL,
  [_ActionDateTime] [datetime2] NOT NULL,
  [SourceRecordId] [int] NOT NULL,
  [LoadDateTime] [datetime2] NOT NULL,
  CONSTRAINT [PK_Contracts_Id] PRIMARY KEY CLUSTERED ([Id])
)
ON [PRIMARY]
GO