DECLARE @LastExecutionDateTime DATETIME2 = ?;
DECLARE @CurentExecutionDateTime DATETIME2 = ?;


SELECT MainData.id,
       MainData.gid,
       MainData.MFO,
       MainData.PaymentAccount,
       MainData.RecipientGID,
       MainData.AmountUAH,
       MainData.Commission,
       MainData.DateTransferToAccounting,
       MainData.PaymentDate,
       MainData.Notes,
       MainData.Deleted,
       MainData.AmountEuro,
       MainData.Amount,
       MainData.CurrencyTypeGID,
       MainData.CalculationGID,
       MainData.AccountStatusGID,
       MainData.AccountPurposeGID,
       MainData.AddUserGID,
       MainData.FolderNumber,
       MainData.ActSignDate,
       MainData.IsExported,
       MainData.ActNumber,
       MainData.AuthorGID,
       MainData.RefusalDate,
       MainData.RefusalLetterNumber,
       MainData.RefusalReason,
       MainData.RequirementStatusGID,
       MainData.PaymentPurpose,
       MainData.TransferNumber,
       MainData.CalculationDate,
       MainData.ExportDate,
       MainData.ExportSuccessDate,
       MainData.OrderAccepted,
       MainData.OrderDate,
       MainData.OrderNumber,
       MainData.PaymentPeriodsCount,
       MainData.PaymentPeriodDate,
       MainData.PaymentPeriodAmountFirst,
       MainData.PaymentPeriodAmount,
       MainData.LogCreateDate,
       MainData.LogActionDate,
       MainData.SourceIdentity,
       MainData.LoadDatetime
FROM
(
    SELECT src.id,
           src.gid,
           src.MFO,
           src.PaymentAccount,
           src.RecipientGID,
           src.AmountUAH,
           src.Commission,
           src.DateTransferToAccounting,
           src.PaymentDate,
           src.Notes,
           src.Deleted,
           src.AmountEuro,
           src.Amount,
           src.CurrencyTypeGID,
           src.CalculationGID,
           src.AccountStatusGID,
           src.AccountPurposeGID,
           src.AddUserGID,
           src.FolderNumber,
           src.ActSignDate,
           src.IsExported,
           src.ActNumber,
           src.AuthorGID,
           src.RefusalDate,
           src.RefusalLetterNumber,
           src.RefusalReason,
           src.RequirementStatusGID,
           src.PaymentPurpose,
           src.TransferNumber,
           src.CalculationDate,
           src.ExportDate,
           src.ExportSuccessDate,
           src.OrderAccepted,
           src.OrderDate,
           src.OrderNumber,
           src.PaymentPeriodsCount,
           src.PaymentPeriodDate,
           src.PaymentPeriodAmountFirst,
           src.PaymentPeriodAmount,
           COALESCE(lg.[_CreateDate], CONVERT(DATETIME, '20100101', 112)) AS [LogCreateDate],
           COALESCE(lg.[_ActionDate], CONVERT(DATETIME, '20100101', 112)) AS [LogActionDate],
           @@SERVERNAME AS SourceIdentity,
           CURRENT_TIMESTAMP AS LoadDatetime
    FROM dbo.Payables AS src
    OUTER APPLY
    (
        SELECT MIN(L.ActionDate) AS [_CreateDate],
               MAX(L.ActionDate) AS [_ActionDate]
        FROM log.Payables AS L
        WHERE L.LoggedEntityGID = src.gid
        GROUP BY L.LoggedEntityGID
    ) AS lg
) AS MainData
WHERE MainData.[LogCreateDate] > @LastExecutionDateTime
      AND MainData.[LogActionDate] <= @CurentExecutionDateTime
