CREATE TABLE [Uran].[CommissarExaminations] (
  [id] [int] NOT NULL,
  [gid] [uniqueidentifier] NOT NULL ROWGUIDCOL,
  [CaseGID] [uniqueidentifier] NOT NULL,
  [Number] [nvarchar](50) NOT NULL,
  [Date] [datetime] NULL,
  [PostAddressGID] [uniqueidentifier] NULL,
  [Address] [nvarchar](255) NULL,
  [MobileCommissarGID] [uniqueidentifier] NULL,
  [ActualDate] [datetime] NULL,
  [IsFinished] [bit] NULL,
  [Notes] [nvarchar](1024) NULL,
  [BackToDirectionDate] [datetime] NULL,
  [AttachedToCaseDate] [datetime] NULL,
  [SentToAccountsCenterDate] [datetime] NULL,
  [AuthorGID] [uniqueidentifier] NULL,
  [TypeGID] [uniqueidentifier] NOT NULL,
  [StatusGID] [uniqueidentifier] NOT NULL,
  [ActualPostAddressGID] [uniqueidentifier] NULL,
  [ActualAddress] [nvarchar](255) NULL,
  [ObjectName] [nvarchar](255) NOT NULL,
  [ObjectGID] [uniqueidentifier] NULL,
  [SecurityTypeGID] [uniqueidentifier] NOT NULL,
  [ServiceStationGID] [uniqueidentifier] NULL,
  [BranchGID] [uniqueidentifier] NULL,
  [Deleted] [bit] NOT NULL,
  [ExpertAppraiserGID] [uniqueidentifier] NULL,
  [CreateDate] [datetime] NOT NULL,
  [LogCreateDateTime] [datetime2] NOT NULL,
  [LogActionDateTime] [datetime2] NOT NULL,
  [RecordSource] [nvarchar](128) NOT NULL,
  [LoadDateTime] [datetime2] NOT NULL,
  CONSTRAINT [PK_CommissarExaminations_Id] PRIMARY KEY CLUSTERED ([id]) ON [DATA]
)
ON [DATA]
GO