CREATE TABLE [Uran].[Payables] (
  [id] [int] NOT NULL,
  [gid] [uniqueidentifier] NOT NULL,
  [MFO] [nvarchar](255) NULL,
  [PaymentAccount] [nvarchar](255) NULL,
  [RecipientGID] [uniqueidentifier] NULL,
  [AmountUAH] [decimal](18, 2) NULL,
  [Commission] [money] NULL,
  [DateTransferToAccounting] [datetime] NULL,
  [PaymentDate] [datetime] NULL,
  [Notes] [nvarchar](255) NULL,
  [Deleted] [bit] NOT NULL,
  [AmountEuro] [money] NULL,
  [Amount] [money] NULL,
  [CurrencyTypeGID] [uniqueidentifier] NULL,
  [CalculationGID] [uniqueidentifier] NULL,
  [AccountStatusGID] [uniqueidentifier] NULL,
  [AccountPurposeGID] [uniqueidentifier] NULL,
  [AddUserGID] [uniqueidentifier] NULL,
  [FolderNumber] [int] NOT NULL,
  [ActSignDate] [datetime] NULL,
  [IsExported] [bit] NOT NULL,
  [ActNumber] [nvarchar](50) NULL,
  [AuthorGID] [uniqueidentifier] NULL,
  [RefusalDate] [datetime] NULL,
  [RefusalLetterNumber] [nvarchar](50) NULL,
  [RefusalReason] [nvarchar](2000) NULL,
  [RequirementStatusGID] [uniqueidentifier] NULL,
  [PaymentPurpose] [nvarchar](2000) NULL,
  [TransferNumber] [nvarchar](255) NULL,
  [CalculationDate] [datetime] NULL,
  [ExportDate] [datetime] NULL,
  [ExportSuccessDate] [datetime] NULL,
  [OrderAccepted] [bit] NOT NULL,
  [OrderDate] [datetime] NULL,
  [OrderNumber] [nvarchar](50) NULL,
  [PaymentPeriodsCount] [int] NULL,
  [PaymentPeriodDate] [datetime] NULL,
  [PaymentPeriodAmountFirst] [decimal](18, 2) NULL,
  [PaymentPeriodAmount] [decimal](18, 2) NULL,
  [LogCreateDateTime] [datetime2] NOT NULL,
  [LogActionDateTime] [datetime2] NOT NULL,
  [RecordSource] [nvarchar](10) NOT NULL,
  [LoadDateTime] [datetime2] NOT NULL,
  CONSTRAINT [PK_Payables_Id] PRIMARY KEY CLUSTERED ([id])
)
ON [PRIMARY]
GO