CREATE TABLE [Uran].[Cases] (
  [id] [bigint] NOT NULL,
  [gid] [uniqueidentifier] NOT NULL,
  [Number] [nvarchar](255) NOT NULL,
  [InnerNumber] [nvarchar](50) NOT NULL,
  [ClaimTypeGID] [uniqueidentifier] NOT NULL,
  [StatusGID] [uniqueidentifier] NOT NULL,
  [ResponsibleGID] [uniqueidentifier] NOT NULL,
  [Year] [int] NOT NULL,
  [EventGID] [uniqueidentifier] NOT NULL,
  [BranchGID] [uniqueidentifier] NULL,
  [IsRegressPossible] [bit] NULL,
  [AddDate] [datetime] NOT NULL,
  [AddUserGID] [uniqueidentifier] NOT NULL,
  [PinCode] [nvarchar](7) NULL,
  [Executor] [nvarchar](255) NULL,
  [ForumTopicGID] [uniqueidentifier] NULL,
  [AuthorGID] [uniqueidentifier] NULL,
  [WorkflowGID] [uniqueidentifier] NULL,
  [PolisNumber] [nvarchar](max) NULL,
  [InsuredName] [nvarchar](max) NULL,
  [InsuredObjectName] [nvarchar](max) NULL,
  [ParticipantFaceNames] [nvarchar](max) NULL,
  [ParticipantObjectNames] [nvarchar](max) NULL,
  [LastModifiedAuthorGID] [uniqueidentifier] NULL,
  [LastModifiedDate] [datetime] NULL,
  [Deleted] [bit] NOT NULL,
  [CreateDate] [datetime] NOT NULL,
  [LogCreateDateTime] [datetime2] NOT NULL,
  [LogActionDateTime] [datetime2] NOT NULL,
  [RecordSource] [nvarchar](128) NOT NULL,
  [LoadDateTime] [datetime2] NOT NULL,
  CONSTRAINT [PK_Cases_Id] PRIMARY KEY CLUSTERED ([id]) ON [DATA]
)
ON [DATA]
TEXTIMAGE_ON [DATA]
GO