CREATE TABLE [Uran].[PayableDetails] (
  [id] [bigint] NOT NULL,
  [gid] [uniqueidentifier] NOT NULL ROWGUIDCOL,
  [ParentGID] [uniqueidentifier] NULL,
  [PayableGID] [uniqueidentifier] NOT NULL,
  [OwnerGID] [uniqueidentifier] NULL,
  [OwnerName] [nvarchar](255) NULL,
  [RepresentativePayment] [bit] NOT NULL,
  [RepresentativeGID] [uniqueidentifier] NULL,
  [RepresentativeName] [nvarchar](255) NULL,
  [AttorneyDate] [datetime] NULL,
  [AttorneyNumber] [nvarchar](50) NULL,
  [PaymentTypeGID] [uniqueidentifier] NULL,
  [PartnerGID] [uniqueidentifier] NULL,
  [BankGID] [uniqueidentifier] NULL,
  [BankName] [nvarchar](255) NULL,
  [RecipientName] [nvarchar](255) NULL,
  [RecipientIdentificationCode] [nvarchar](15) NULL,
  [BankAccount] [nvarchar](50) NULL,
  [PersonalAccount] [nvarchar](50) NULL,
  [OffsetPolisNumber] [nvarchar](50) NULL,
  [PaymentPurpose] [nvarchar](255) NULL,
  [CreateDate] [datetime] NULL,
  [AdjustmentTypeGID] [uniqueidentifier] NULL,
  [AdjustmentAccountingDate] [datetime] NULL,
  [AdjustmentCancelDate] [datetime] NULL,
  [ExportDate] [datetime] NULL,
  [ExportSuccessDate] [datetime] NULL,
  [AuthorGID] [uniqueidentifier] NULL,
  [BankMFO] [nvarchar](10) NULL,
  [AddUserGID] [uniqueidentifier] NOT NULL,
  [AddDate] [datetime] NOT NULL,
  [PaymentPurposeTemplateGID] [uniqueidentifier] NULL,
  [RecipientBankName] [nvarchar](255) NULL,
  [RefusalDate] [datetime] NULL,
  [RefusalReason] [nvarchar](2000) NULL,
  [RecipientGID] [uniqueidentifier] NULL,
  [AccountGID] [uniqueidentifier] NULL,
  [ProductGID] [uniqueidentifier] NULL,
  [LogCreateDateTime] [datetime2] NOT NULL,
  [LogActionDateTime] [datetime2] NOT NULL,
  [RecordSource] [nvarchar](128) NOT NULL,
  [LoadDateTime] [datetime2] NOT NULL,
  CONSTRAINT [PK_PayableDetails_Id] PRIMARY KEY CLUSTERED ([id]) ON [DATA]
)
ON [DATA]
GO